platform :osx, '10.7'

pod 'MASShortcut'
pod 'DBPrefsWindowController'
pod 'SPMediaKeyTap'
pod 'INAppStoreWindow', :git => 'git://github.com/jhildensperger/INAppStoreWindow.git'
pod 'AFNetworking', '1.0RC2'
pod 'INKeychainAccess'
pod 'HIDRemoteSDK'
pod 'OEGridView'
